#!/bin/bash
PATH=/bin:/usr/bin

RPMDIR=$HOME/rpmbuild
REPODIR=/tmp/dafrito/repo.$$
PROJECTDIR=$HOME/projects

#git diff --exit-code || die "Refusing to build from dirty repo"

die() {
	echo $* 1>&2
	exit 1
}

mkdir -v $REPODIR || die "Could not create repo directory"
rsync -ihavz dafrito@linode:/srv/dafrito/rpm/ $REPODIR/
exit
trap 'rm -rf $REPODIR' INT EXIT

IFS='
'

unsigned=

sync_package() {
	IFS='	
'
	set - $*
	unset IFS
	local name=$1
	local path=$PROJECTDIR/$name
	pushd $path || die "Failed to change directory to $path"
	make rpm || die "Build failed for $name"
	for rpm in `rpm --specfile $RPMDIR/SPECS/$name.spec -q`; do
		rpmfile="$RPMDIR/RPMS/`echo $rpm | sed -nre 's%^.*\.([^.]+)$%\1%p'`/$rpm.rpm"
		if [ ! -f $REPODIR/`basename $rpmfile` ]; then
			cp -v -p $rpmfile $REPODIR || die "Failed to copy package: $rpmfile"
			unsigned="$unsigned $rpm.rpm"
		fi
	done
	popd
}

for package in $(<packages); do
	echo $package
	sync_package $package
done

echo
if [ -n "$unsigned" ]; then
	cd $REPODIR
	echo "The following packages will be updated and require a signature:"
	for rpm in $unsigned; do
		basename $rpm .rpm
	done
	failures=0
	while true; do
		rpm --addsign $unsigned && break
		let failures++
		if [ $failures -gt 3 ]; then
			die "Failed to sign packages"
		fi
	done
	createrepo $REPODIR
	rsync -ihavz $REPODIR/ dafrito@linode:/srv/dafrito/rpm/
else
	echo "No packages need to be updated"
fi
