#!/bin/bash
PATH=/bin:/usr/bin

RPMDIR=$HOME/rpmbuild
REPODIR=/tmp/dafrito/repo.$$
CLEAN=clean
PROJECTDIR=$HOME/projects

die() {
	echo $* 1>&2
	exit 1
}

mkdir -v $REPODIR || die "Could not create repo directory"
trap 'rm -rf $REPODIR' INT EXIT

IFS='
'

get_rpm_name() {
	while read rpm; do
		arch=`echo $rpm | sed -nre 's%^.*\.([^.]+)$%\1%p'`
		echo $RPMDIR/RPMS/$arch/$rpm.rpm
	done
}

sync_package() {
	IFS='	
'
	set - $*
	unset IFS
	local name=$1
	local path=$PROJECTDIR/$name
	pushd $path || die "Failed to change directory to $path"
	make $CLEAN rpm || die "Build failed for $name"
	cp -p -v -t $REPODIR `rpm --specfile ./$name.spec -q | get_rpm_name` || die "Failed to copy packages"
	popd
}

#git diff --exit-code || die "Refusing to build from dirty repo"
for package in $(<packages); do
	echo $package
	sync_package $package
done

echo "Signing packages"
failures=0
while true; do
	rpm --addsign $REPODIR/*.rpm && break
	let failures++
	if [ $failures -gt 3 ]; then
		die "Failed to sign packages"
	fi
done
createrepo $REPODIR
rsync -ihavz --delete $REPODIR/ dafrito@linode:/srv/dafrito/rpm/
